// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcu2qGXOCLBYb_uZiK5qsoLnlzaNZyuv4',
    appId: '1:508029305779:web:5e8257194b31f7eb5981c6',
    messagingSenderId: '508029305779',
    projectId: 'fir-2-e11f0',
    authDomain: 'fir-2-e11f0.firebaseapp.com',
    storageBucket: 'fir-2-e11f0.appspot.com',
    measurementId: 'G-DJB6WY82Q7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA38jXrLWsI7tYfYU5nMwS8biBU1Aq96TU',
    appId: '1:508029305779:android:ac6eba8ceb5dc6cc5981c6',
    messagingSenderId: '508029305779',
    projectId: 'fir-2-e11f0',
    storageBucket: 'fir-2-e11f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHoElIleKYGsGARDE7V-1oNN0AYgtJh1A',
    appId: '1:508029305779:ios:c6bb624f2133672b5981c6',
    messagingSenderId: '508029305779',
    projectId: 'fir-2-e11f0',
    storageBucket: 'fir-2-e11f0.appspot.com',
    iosBundleId: 'com.example.firebase2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHoElIleKYGsGARDE7V-1oNN0AYgtJh1A',
    appId: '1:508029305779:ios:c6bb624f2133672b5981c6',
    messagingSenderId: '508029305779',
    projectId: 'fir-2-e11f0',
    storageBucket: 'fir-2-e11f0.appspot.com',
    iosBundleId: 'com.example.firebase2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcu2qGXOCLBYb_uZiK5qsoLnlzaNZyuv4',
    appId: '1:508029305779:web:bcb63c7a0c28d3cd5981c6',
    messagingSenderId: '508029305779',
    projectId: 'fir-2-e11f0',
    authDomain: 'fir-2-e11f0.firebaseapp.com',
    storageBucket: 'fir-2-e11f0.appspot.com',
    measurementId: 'G-F4PSMSSS4W',
  );

}